spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  liquibase:
    contexts: prod
  config:
    import: optional:cloud.properties, optional:db.properties

app:
  cloudinary:
    cloud-name: ${cloud_name}
    api-key: ${api_key}
    api-secret: ${api_secret}
  storage:
    image-prefix: ""
